# Generated by Django 2.0.4 on 2020-02-03 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doctor',
            new_name='Doctor',
        ),
    ]
