# Generated by Django 2.0.4 on 2020-02-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0002_auto_20200203_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField()),
                ('phone', models.PositiveIntegerField()),
                ('discount', models.FloatField(blank=True, default=0, null=True)),
                ('number_of_sales', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('number_of_views', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('avg_rate', models.FloatField(blank=True, default=0, null=True)),
                ('description', models.TextField()),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
